#!/bin/bash
# plan-content.sh — Auto-replenishes the blog content queue
#
# Runs on: dexterslabserver (Linux)
# Triggered by: n8n cron workflow (1st of each month)
#
# Flow:
#   1. Pull latest main
#   2. Read existing posts and queue to find gaps
#   3. Use Claude CLI to plan 8-12 new topics
#   4. Append to _data/content-queue.yml
#   5. Create PR for owner review

# Ensure ~/.local/bin is in PATH (needed for non-interactive SSH sessions like n8n)
export PATH="/home/d-exe/.local/bin:$PATH"

set -euo pipefail

REPO_DIR="/home/d-exe/TitanCleaningService"
QUEUE_FILE="$REPO_DIR/_data/content-queue.yml"
POSTS_DIR="$REPO_DIR/_posts"
TODAY=$(date +%Y-%m-%d)
MONTH=$(date +%B)
YEAR=$(date +%Y)
GH="/home/d-exe/.local/bin/gh"

cd "$REPO_DIR"
git checkout main
git pull origin main

# ── 1. Gather context ────────────────────────────────────────────

# Get existing post titles
EXISTING_POSTS=$(ls "$POSTS_DIR"/*.md 2>/dev/null | xargs -I{} head -5 {} | grep "^title:" | sed 's/title: //' | sed 's/"//g' || echo "none")

# Get current queue topics
QUEUE_TOPICS=$(python3 -c "
import yaml
with open('$QUEUE_FILE') as f:
    queue = yaml.safe_load(f)
if queue:
    for item in queue:
        print(f\"- {item['title']} [{item['status']}]\")
else:
    print('Queue is empty')
")

# Count pending topics
PENDING_COUNT=$(python3 -c "
import yaml
with open('$QUEUE_FILE') as f:
    queue = yaml.safe_load(f)
count = sum(1 for item in (queue or []) if item['status'] == 'pending')
print(count)
")

echo "$(date): Content planning for ${MONTH} ${YEAR}"
echo "  Pending topics: ${PENDING_COUNT}"

# Only replenish if fewer than 8 pending topics remain
if [ "$PENDING_COUNT" -ge 8 ]; then
    echo "$(date): Queue has ${PENDING_COUNT} pending topics. No replenishment needed."
    exit 0
fi

TOPICS_NEEDED=$((12 - PENDING_COUNT))
echo "$(date): Need ${TOPICS_NEEDED} new topics"

BRANCH="content-plan/${TODAY}"

git checkout -b "$BRANCH"

# ── 2. Generate new topics with Claude CLI ────────────────────────

NEW_TOPICS=$(claude -p --output-format text "You are a content strategist for Titan Cleaning Service (titancleaningservice.ca), a carpet and cleaning company in Victoria, BC. Services: carpet cleaning, upholstery cleaning, tile & grout cleaning, mattress cleaning, pressure washing, floor waxing & stripping. Service areas: Victoria, Langford, Sidney, Saanich, Oak Bay, Mill Bay, Duncan, Nanaimo, Ladysmith.

The current month is ${MONTH} ${YEAR}. Plan ${TOPICS_NEEDED} new blog post topics.

EXISTING POSTS (do NOT duplicate these):
${EXISTING_POSTS}

CURRENT QUEUE (do NOT duplicate these):
${QUEUE_TOPICS}

CONTENT CLUSTERS to rotate through:
1. Carpet Cleaning (primary money topic)
2. Upholstery / Furniture Cleaning
3. Tile & Grout
4. Pressure Washing / Outdoor
5. Mattress & Bedroom Health
6. Local / Vancouver Island specific
7. Seasonal content for ${MONTH}

SEASONAL CONTEXT for ${MONTH}:
- Spring (Mar-May): spring cleaning surge, pressure washing demand, deck prep, move-out season
- Summer (Jun-Aug): outdoor focus, BBQ season, moving peak, commercial floor maintenance
- Fall (Sep-Nov): pre-holiday cleaning, guest preparation, year-end commercial budgets
- Winter (Dec-Feb): post-holiday stain removal, indoor air quality, mould/dampness, New Year deep clean

TARGET KEYWORDS: Focus on long-tail keywords real people search for. Each topic should target a specific keyword phrase.

OUTPUT FORMAT: Output ONLY valid YAML entries (no markdown fences, no explanation), formatted exactly like this:

- slug: example-post-slug
  title: \"Example Post Title\"
  target_keyword: \"example long tail keyword\"
  cluster: carpet
  tags: [Carpet Cleaning, Tips]
  brief: |
    2-3 sentence content brief explaining what to cover.
    Include specific points, data to mention, and internal pages to link to.
  status: pending
  publish_date:

Output ${TOPICS_NEEDED} topics. Ensure variety across clusters. Include at least 1-2 seasonal topics for ${MONTH}.")

# ── 3. Append to queue file ──────────────────────────────────────

echo "" >> "$QUEUE_FILE"
echo "# ── ${MONTH} ${YEAR} (auto-planned) ──────────────────────────────" >> "$QUEUE_FILE"
echo "" >> "$QUEUE_FILE"
echo "$NEW_TOPICS" >> "$QUEUE_FILE"

# ── 4. Commit and create PR ──────────────────────────────────────

git add "$QUEUE_FILE"
git commit -m "Plan blog content for ${MONTH} ${YEAR}"
git push -u origin "$BRANCH"

$GH pr create \
    --title "Content Plan: ${MONTH} ${YEAR}" \
    --body "$(cat <<EOF
## Monthly Content Plan

**Month:** ${MONTH} ${YEAR}
**New topics added:** ${TOPICS_NEEDED}
**Existing pending:** ${PENDING_COUNT}

### Review the Topics

Please review the new topics added to \`_data/content-queue.yml\`. You can:
- Edit topic titles or briefs before merging
- Remove topics you don't want
- Add your own topic ideas
- Reorder priorities

Once merged, the blog generator will start producing these posts on schedule.

---
*Auto-generated by the Titan content planning pipeline*
EOF
)"

git checkout main

echo "$(date): Done — Content plan PR created for ${MONTH} ${YEAR}"
